#!/bin/bash

OSD="aosd_cat -p 4 -t 2 -n 44 -w 0 -R white -b 5 -s 100 -r 150 -f 100 -u 1000 -o 200"
echo "simsalabim..!" | `$OSD`
# do some magic
xrandr --auto

echo "autoconfiguring screens" | `$OSD`
# turn on dual screen and put VGA to the left of builtin
xrandr --output VGA --left-of LVDS
